<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];


$type = $_POST['type'];


if ($_POST["type"] == 1) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_inv_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Patient Reports - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>
    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th rowspan="2">Sl. No</th>
                <th rowspan="2">No. of Patients</th>
                <th colspan="3">OPD</th>
                <th colspan="3">IPD</th>
                <th colspan="3">Emergency</th>
                <th colspan="4">Total</th>
            </tr>
            <tr>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $opd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `opd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '1' AND `pat_type`='OPD'"));
            $nrhm_opd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_opd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '3' AND `pat_type`='OPD'"));

            $ipd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `ipd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '2' AND `pat_type`='IPD'"));
            $nrhm_ipd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_ipd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '3' AND `pat_type`='IPD'"));

            $emg = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `emg_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '4' AND `pat_type`='EMER'"));
            $nrhm_emg = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_emg_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '5'"));

            $tot_opd = $opd_count['opd_total_count'] + $nrhm_opd_count['nrhm_opd_total_count'];
            $tot_ipd = $ipd_count['ipd_total_count'] + $nrhm_ipd_count['nrhm_ipd_total_count'];
            $tot_emg = $emg['emg_total_count'] + $nrhm_emg['nrhm_emg_total_count'];
            $grand_tot_gen = $opd_count['opd_total_count'] + $ipd_count['ipd_total_count'] + $emg['emg_total_count'];
            $grand_tot_nr = $nrhm_opd_count['nrhm_opd_total_count'] + $nrhm_ipd_count['nrhm_ipd_total_count'] + $nrhm_emg['nrhm_emg_total_count'];

            $grand_tot = $tot_opd + $tot_ipd + $tot_emg;


            function get_gender_count($link, $fdate, $tdate, $type, $pat_types, $gender)
            {
                $query = "
                    SELECT COUNT(*) AS count
                    FROM uhid_and_opdid u
                    JOIN patient_info p ON u.patient_id = p.patient_id
                    WHERE u.date BETWEEN '$fdate' AND '$tdate'
                    AND u.type = '$type'
                    AND p.sex = '$gender'
                ";

                if (!empty($pat_types)) {
                    if (is_array($pat_types)) {
                        $escaped_types = array_map(function ($pt) use ($link) {
                            return "'" . mysqli_real_escape_string($link, $pt) . "'";
                        }, $pat_types);
                        $pat_type_str = implode(',', $escaped_types);
                        $query .= " AND u.pat_type IN ($pat_type_str)";
                    } else {
                        $query .= " AND u.pat_type = '" . mysqli_real_escape_string($link, $pat_types) . "'";
                    }
                }

                $result = mysqli_fetch_array(mysqli_query($link, $query));
                return $result['count'];
            }


            $opd_male_gen = get_gender_count($link, $fdate, $tdate, '1', 'OPD', 'Male');
            $opd_male_nr = get_gender_count($link, $fdate, $tdate, '3', 'OPD', 'Male');
            $opd_female_gen = get_gender_count($link, $fdate, $tdate, '1', 'OPD', 'Female');
            $opd_female_nr = get_gender_count($link, $fdate, $tdate, '3', 'OPD', 'Female');

            $ipd_male_gen = get_gender_count($link, $fdate, $tdate, '2', 'IPD', 'Male');
            $ipd_male_nr = get_gender_count($link, $fdate, $tdate, '3', 'IPD', 'Male');
            $ipd_female_gen = get_gender_count($link, $fdate, $tdate, '2', 'IPD', 'Female');
            $ipd_female_nr = get_gender_count($link, $fdate, $tdate, '3', 'IPD', 'Female');


            $emg_male_gen = get_gender_count($link, $fdate, $tdate, '4', 'EMER', 'Male');
            $emg_female_gen = get_gender_count($link, $fdate, $tdate, '4', 'EMER', 'Female');

            $emg_male_nr = get_gender_count($link, $fdate, $tdate, '5', ['OPD', 'IPD'], 'Male');
            $emg_female_nr = get_gender_count($link, $fdate, $tdate, '5', ['OPD', 'IPD'], 'Female');

            ?>


            <tr>
                <td>1</td>
                <td>Total Patients</td>
                <td><?php echo $opd_count['opd_total_count'] ?></td>
                <td><?php echo $nrhm_opd_count['nrhm_opd_total_count'] ?></td>
                <td><?php echo $tot_opd; ?></td>
                <td><?php echo $ipd_count['ipd_total_count'] ?></td>
                <td><?php echo $nrhm_ipd_count['nrhm_ipd_total_count'] ?></td>
                <td><?php echo $tot_ipd; ?></td>
                <td><?php echo $emg['emg_total_count'] ?></td>
                <td><?php echo $nrhm_emg['nrhm_emg_total_count'] ?></td>
                <td><?php echo $tot_emg; ?></td>
                <td><?php echo $grand_tot_gen; ?></td>
                <td><?php echo $grand_tot_nr; ?></td>
                <td><strong><?php echo $grand_tot; ?></strong></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Male</td>
                <td><?php echo $opd_male_gen; ?></td>
                <td><?php echo $opd_male_nr; ?></td>
                <td><?php echo $opd_male_gen + $opd_male_nr; ?></td>
                <td><?php echo $ipd_male_gen; ?></td>
                <td><?php echo $ipd_male_nr; ?></td>
                <td><?php echo $ipd_male_gen + $ipd_male_nr; ?></td>
                <td><?php echo $emg_male_gen; ?></td>
                <td><?php echo $emg_male_nr; ?></td>
                <td><?php echo $emg_male_gen + $emg_male_nr; ?></td>
                <td><?php echo $opd_male_gen + $ipd_male_gen + $emg_male_gen; ?></td>
                <td><?php echo $opd_male_nr + $ipd_male_nr + $emg_male_nr; ?></td>
                <td><strong><?php echo ($opd_male_gen + $opd_male_nr + $ipd_male_gen + $ipd_male_nr + $emg_male_gen + $emg_male_nr); ?>
                    </strong></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Female</td>
                <td><?php echo $opd_female_gen; ?></td>
                <td><?php echo $opd_female_nr; ?></td>
                <td><?php echo $opd_female_gen + $opd_female_nr; ?></td>
                <td><?php echo $ipd_female_gen; ?></td>
                <td><?php echo $ipd_female_nr; ?></td>
                <td><?php echo $ipd_female_gen + $ipd_female_nr; ?></td>
                <td><?php echo $emg_female_gen; ?></td>
                <td><?php echo $emg_female_nr; ?></td>
                <td><?php echo $emg_female_gen + $emg_female_nr; ?></td>
                <td><?php echo $opd_female_gen + $ipd_female_gen + $emg_female_gen; ?></td>
                <td><?php echo $opd_female_nr + $ipd_female_nr + $emg_female_nr; ?></td>
                <td><strong><?php echo ($opd_female_gen + $opd_female_nr + $ipd_female_gen + $ipd_female_nr + $emg_female_gen + $emg_female_nr); ?>
                    </strong></td>
            </tr>

        </tbody>
    </table>



    <?php
}

if ($_POST["type"] == 2) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_inv_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Parameter Wise Reports - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>

    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th rowspan="2">Sl. No</th>
                <th rowspan="2">Parameter</th>
                <th colspan="3">OPD</th>
                <th colspan="3">IPD</th>
                <th colspan="3">Emergency</th>
                <th colspan="4">Total</th>
            </tr>
            <tr>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
            </tr>
        </thead>
        <?php
        function highlight($value)
        {
            return $value > 0 ? ' style="background-color: #d4edda;"' : '';
        }
        ?>

        <tbody>
            <?php
            $no = 1;

            $sum_opd_gen = 0;
            $sum_opd_nr = 0;
            $sum_ipd_gen = 0;
            $sum_ipd_nr = 0;
            $sum_emg_gen = 0;
            $sum_emg_nr = 0;

            $param_query = mysqli_query($link, "
                SELECT DISTINCT tr.paramid, p.Name 
                FROM testresults tr
                JOIN Parameter_old p ON tr.paramid = p.ID
                WHERE tr.date BETWEEN '$fdate' AND '$tdate'
                ORDER BY p.Name ASC
            ");

            while ($param_row = mysqli_fetch_array($param_query)) {
                $param_id = $param_row['paramid'];
                $param_name = $param_row['Name'];

                $count_query = "
                    SELECT 
                        SUM(CASE WHEN u.type='1' AND u.pat_type='OPD' THEN 1 ELSE 0 END) AS opd_gen,
                        SUM(CASE WHEN u.type='3' AND u.pat_type='OPD' THEN 1 ELSE 0 END) AS opd_nr,
                        SUM(CASE WHEN u.type='2' AND u.pat_type='IPD' THEN 1 ELSE 0 END) AS ipd_gen,
                        SUM(CASE WHEN u.type='3' AND u.pat_type='IPD' THEN 1 ELSE 0 END) AS ipd_nr,
                        SUM(CASE WHEN u.type='4' AND u.pat_type='EMER' THEN 1 ELSE 0 END) AS emg_gen,
                        SUM(CASE WHEN u.type='5' THEN 1 ELSE 0 END) AS emg_nr
                    FROM testresults tr
                    JOIN uhid_and_opdid u ON tr.opd_id = u.opd_id
                    WHERE tr.paramid = '$param_id' AND u.date BETWEEN '$fdate' AND '$tdate'
                ";

                $count_result = mysqli_fetch_array(mysqli_query($link, $count_query));

                $opd_gen = $count_result['opd_gen'];
                $opd_nr = $count_result['opd_nr'];
                $ipd_gen = $count_result['ipd_gen'];
                $ipd_nr = $count_result['ipd_nr'];
                $emg_gen = $count_result['emg_gen'];
                $emg_nr = $count_result['emg_nr'];

                $opd_total = $opd_gen + $opd_nr;
                $ipd_total = $ipd_gen + $ipd_nr;
                $emg_total = $emg_gen + $emg_nr;
                $grand_gen = $opd_gen + $ipd_gen + $emg_gen;
                $grand_nr = $opd_nr + $ipd_nr + $emg_nr;
                $grand_all = $grand_gen + $grand_nr;

                $sum_opd_gen += $opd_gen;
                $sum_opd_nr += $opd_nr;
                $sum_ipd_gen += $ipd_gen;
                $sum_ipd_nr += $ipd_nr;
                $sum_emg_gen += $emg_gen;
                $sum_emg_nr += $emg_nr;
                ?>
                <tr>
                    <td><?php echo $no++; ?></td>
                    <td><?php echo $param_name; ?></td>
                    <td<?php echo highlight($opd_gen); ?>><?php echo $opd_gen; ?></td>
                        <td<?php echo highlight($opd_nr); ?>><?php echo $opd_nr; ?></td>
                            <td<?php echo highlight($opd_total); ?>><?php echo $opd_total; ?></td>
                                <td<?php echo highlight($ipd_gen); ?>><?php echo $ipd_gen; ?></td>
                                    <td<?php echo highlight($ipd_nr); ?>><?php echo $ipd_nr; ?></td>
                                        <td<?php echo highlight($ipd_total); ?>><?php echo $ipd_total; ?></td>
                                            <td<?php echo highlight($emg_gen); ?>><?php echo $emg_gen; ?></td>
                                                <td<?php echo highlight($emg_nr); ?>><?php echo $emg_nr; ?></td>
                                                    <td<?php echo highlight($emg_total); ?>><?php echo $emg_total; ?></td>
                                                        <td<?php echo highlight($grand_gen); ?>><?php echo $grand_gen; ?></td>
                                                            <td<?php echo highlight($grand_nr); ?>><?php echo $grand_nr; ?></td>
                                                                <td style="background-color: bisque;">
                                                                    <strong><?php echo $grand_all; ?></strong>
                                                                </td>

                </tr>
                <?php
            }

            $final_opd_total = $sum_opd_gen + $sum_opd_nr;
            $final_ipd_total = $sum_ipd_gen + $sum_ipd_nr;
            $final_emg_total = $sum_emg_gen + $sum_emg_nr;
            $final_grand_gen = $sum_opd_gen + $sum_ipd_gen + $sum_emg_gen;
            $final_grand_nr = $sum_opd_nr + $sum_ipd_nr + $sum_emg_nr;
            $final_grand_all = $final_grand_gen + $final_grand_nr;
            ?>
        </tbody>


        <tfoot style="font-weight: bold; background: #f0f0f0;">
            <tr>
                <td colspan="2" align="right">Grand Total:</td>
                <td><?php echo $sum_opd_gen; ?></td>
                <td><?php echo $sum_opd_nr; ?></td>
                <td style="background-color: bisque;"><?php echo $final_opd_total; ?></td>
                <td><?php echo $sum_ipd_gen; ?></td>
                <td><?php echo $sum_ipd_nr; ?></td>
                <td style="background-color: bisque;"><?php echo $final_ipd_total; ?></td>
                <td><?php echo $sum_emg_gen; ?></td>
                <td><?php echo $sum_emg_nr; ?></td>
                <td style="background-color: bisque;"><?php echo $final_emg_total; ?></td>
                <td><?php echo $final_grand_gen; ?></td>
                <td><?php echo $final_grand_nr; ?></td>
                <td style="background-color: bisque;"><strong><?php echo $final_grand_all; ?></strong></td>
            </tr>
        </tfoot>




    </table>


    <?php
}



