<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];


$type = $_POST['type'];


if ($_POST["type"] == 1) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_inv_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Patient Reports - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>
    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th rowspan="2">Sl. No</th>
                <th rowspan="2">No. of Patients</th>
                <th colspan="3">OPD</th>
                <th colspan="3">IPD</th>
                <th colspan="3">Emergency</th>
                <th colspan="4">Total</th>
            </tr>
            <tr>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN</th>
                <th>NR</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $opd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `opd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '1' AND `pat_type`='OPD'"));
            $nrhm_opd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_opd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '3' AND `pat_type`='OPD'"));

            $ipd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `ipd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '2' AND `pat_type`='IPD'"));
            $nrhm_ipd_count = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_ipd_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '3' AND `pat_type`='IPD'"));

            $emg = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `emg_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '4' AND `pat_type`='EMER'"));
            $nrhm_emg = mysqli_fetch_array(mysqli_query($link, "SELECT COUNT(`opd_id`) AS `nrhm_emg_total_count` FROM `uhid_and_opdid` WHERE `date` BETWEEN '$fdate' AND '$tdate' AND `type`= '5'"));

            $tot_opd = $opd_count['opd_total_count'] + $nrhm_opd_count['nrhm_opd_total_count'];
            $tot_ipd = $ipd_count['ipd_total_count'] + $nrhm_ipd_count['nrhm_ipd_total_count'];
            $tot_emg = $emg['emg_total_count'] + $nrhm_emg['nrhm_emg_total_count'];
            $grand_tot_gen = $opd_count['opd_total_count'] + $ipd_count['ipd_total_count'] + $emg['emg_total_count'];
            $grand_tot_nr = $nrhm_opd_count['nrhm_opd_total_count'] + $nrhm_ipd_count['nrhm_ipd_total_count'] + $nrhm_emg['nrhm_emg_total_count'];

            $grand_tot = $tot_opd + $tot_ipd + $tot_emg;


            function get_gender_count($link, $fdate, $tdate, $type, $pat_types, $gender)
            {
                $query = "
                    SELECT COUNT(*) AS count
                    FROM uhid_and_opdid u
                    JOIN patient_info p ON u.patient_id = p.patient_id
                    WHERE u.date BETWEEN '$fdate' AND '$tdate'
                    AND u.type = '$type'
                    AND p.sex = '$gender'
                ";

                if (!empty($pat_types)) {
                    if (is_array($pat_types)) {
                        $escaped_types = array_map(function ($pt) use ($link) {
                            return "'" . mysqli_real_escape_string($link, $pt) . "'";
                        }, $pat_types);
                        $pat_type_str = implode(',', $escaped_types);
                        $query .= " AND u.pat_type IN ($pat_type_str)";
                    } else {
                        $query .= " AND u.pat_type = '" . mysqli_real_escape_string($link, $pat_types) . "'";
                    }
                }

                $result = mysqli_fetch_array(mysqli_query($link, $query));
                return $result['count'];
            }


            $opd_male_gen = get_gender_count($link, $fdate, $tdate, '1', 'OPD', 'Male');
            $opd_male_nr = get_gender_count($link, $fdate, $tdate, '3', 'OPD', 'Male');
            $opd_female_gen = get_gender_count($link, $fdate, $tdate, '1', 'OPD', 'Female');
            $opd_female_nr = get_gender_count($link, $fdate, $tdate, '3', 'OPD', 'Female');

            $ipd_male_gen = get_gender_count($link, $fdate, $tdate, '2', 'IPD', 'Male');
            $ipd_male_nr = get_gender_count($link, $fdate, $tdate, '3', 'IPD', 'Male');
            $ipd_female_gen = get_gender_count($link, $fdate, $tdate, '2', 'IPD', 'Female');
            $ipd_female_nr = get_gender_count($link, $fdate, $tdate, '3', 'IPD', 'Female');


            $emg_male_gen = get_gender_count($link, $fdate, $tdate, '4', 'EMER', 'Male');
            $emg_female_gen = get_gender_count($link, $fdate, $tdate, '4', 'EMER', 'Female');

            $emg_male_nr = get_gender_count($link, $fdate, $tdate, '5', ['OPD', 'IPD'], 'Male');
            $emg_female_nr = get_gender_count($link, $fdate, $tdate, '5', ['OPD', 'IPD'], 'Female');

            ?>


            <tr>
                <td>1</td>
                <td>Total Patients</td>
                <td><?php echo $opd_count['opd_total_count'] ?></td>
                <td><?php echo $nrhm_opd_count['nrhm_opd_total_count'] ?></td>
                <td><?php echo $tot_opd; ?></td>
                <td><?php echo $ipd_count['ipd_total_count'] ?></td>
                <td><?php echo $nrhm_ipd_count['nrhm_ipd_total_count'] ?></td>
                <td><?php echo $tot_ipd; ?></td>
                <td><?php echo $emg['emg_total_count'] ?></td>
                <td><?php echo $nrhm_emg['nrhm_emg_total_count'] ?></td>
                <td><?php echo $tot_emg; ?></td>
                <td><?php echo $grand_tot_gen; ?></td>
                <td><?php echo $grand_tot_nr; ?></td>
                <td><strong><?php echo $grand_tot; ?></strong></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Male</td>
                <td><?php echo $opd_male_gen; ?></td>
                <td><?php echo $opd_male_nr; ?></td>
                <td><?php echo $opd_male_gen + $opd_male_nr; ?></td>
                <td><?php echo $ipd_male_gen; ?></td>
                <td><?php echo $ipd_male_nr; ?></td>
                <td><?php echo $ipd_male_gen + $ipd_male_nr; ?></td>
                <td><?php echo $emg_male_gen; ?></td>
                <td><?php echo $emg_male_nr; ?></td>
                <td><?php echo $emg_male_gen + $emg_male_nr; ?></td>
                <td><?php echo $opd_male_gen + $ipd_male_gen + $emg_male_gen; ?></td>
                <td><?php echo $opd_male_nr + $ipd_male_nr + $emg_male_nr; ?></td>
                <td><strong><?php echo ($opd_male_gen + $opd_male_nr + $ipd_male_gen + $ipd_male_nr + $emg_male_gen + $emg_male_nr); ?>
                    </strong></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Female</td>
                <td><?php echo $opd_female_gen; ?></td>
                <td><?php echo $opd_female_nr; ?></td>
                <td><?php echo $opd_female_gen + $opd_female_nr; ?></td>
                <td><?php echo $ipd_female_gen; ?></td>
                <td><?php echo $ipd_female_nr; ?></td>
                <td><?php echo $ipd_female_gen + $ipd_female_nr; ?></td>
                <td><?php echo $emg_female_gen; ?></td>
                <td><?php echo $emg_female_nr; ?></td>
                <td><?php echo $emg_female_gen + $emg_female_nr; ?></td>
                <td><?php echo $opd_female_gen + $ipd_female_gen + $emg_female_gen; ?></td>
                <td><?php echo $opd_female_nr + $ipd_female_nr + $emg_female_nr; ?></td>
                <td><strong><?php echo ($opd_female_gen + $opd_female_nr + $ipd_female_gen + $ipd_female_nr + $emg_female_gen + $emg_female_nr); ?>
                    </strong></td>
            </tr>

        </tbody>
    </table>



    <?php
}

if ($_POST["type"] == 2) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_inv_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Parameter Wise Reports From:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>

    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th rowspan="2">#</th>
                <th rowspan="2">Parameter</th>
                <th colspan="4">OPD</th>
                <th colspan="4">IPD</th>
                <th colspan="4">Emergency</th>
                <th colspan="4">Total</th>
            </tr>
            <tr>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php
            function highlight($value)
            {
                return $value > 0 ? ' style="background-color: #d4edda;"' : '';
            }

            function total_highlight($value)
            {
                return $value > 0 ? ' style="background-color: #fbffd9ff;"' : '';
            }

            function g_total_highlight($value)
            {
                return $value > 0 ? ' style="background-color: #d9e3ffff;"' : '';
            }

            // Initialize grand totals
            $gt = [
                'gen_paid_opd' => 0,
                'gen_free_opd' => 0,
                'opd_nr' => 0,
                'opd_tot' => 0,
                'gen_paid_ipd' => 0,
                'gen_free_ipd' => 0,
                'ipd_nr' => 0,
                'ipd_tot' => 0,
                'gen_paid_emer' => 0,
                'gen_free_emer' => 0,
                'nr_emer' => 0,
                'emer_tot' => 0,
                'paid_total' => 0,
                'free_total' => 0,
                'nr_total' => 0,
                'g_total' => 0
            ];

            $query = "SELECT 
                a.paramid,
                b.Name AS param_name,
                SUM(CASE WHEN ua.type = '1' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_opd,
                SUM(CASE WHEN ua.type = '1' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_opd,
                SUM(CASE WHEN ua.type = '3' AND ua.pat_type = 'OPD' THEN 1 ELSE 0 END) AS opd_nr,

                SUM(CASE WHEN ua.type = '2' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_ipd,
                SUM(CASE WHEN ua.type = '2' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_ipd,
                SUM(CASE WHEN ua.type = '3' AND ua.pat_type = 'IPD' THEN 1 ELSE 0 END) AS ipd_nr,

                SUM(CASE WHEN ua.type = '4' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_emer,
                SUM(CASE WHEN ua.type = '4' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_emer,
                SUM(CASE WHEN ua.type_prefix = 'NRM_EMRG/' THEN 1 ELSE 0 END) AS nr_emer
            FROM 
                testresults a
                JOIN Parameter_old b ON a.paramid = b.ID
                JOIN uhid_and_opdid ua ON a.opd_id = ua.opd_id
            WHERE 
                a.date BETWEEN '$fdate' AND '$tdate'
            GROUP BY 
                a.paramid
            ORDER BY 
                b.Name
        ";


            $res = mysqli_query($link, $query);
            $no = 1;

            while ($row = mysqli_fetch_assoc($res)) {
                $opd_tot = $row['gen_paid_opd'] + $row['gen_free_opd'] + $row['opd_nr'];
                $ipd_tot = $row['gen_paid_ipd'] + $row['gen_free_ipd'] + $row['ipd_nr'];
                $emer_tot = $row['gen_paid_emer'] + $row['gen_free_emer'] + $row['nr_emer'];

                $paid_total = $row['gen_paid_opd'] + $row['gen_paid_ipd'] + $row['gen_paid_emer'];
                $free_total = $row['gen_free_opd'] + $row['gen_free_ipd'] + $row['gen_free_emer'];
                $nr_total = $row['opd_nr'] + $row['ipd_nr'] + $row['nr_emer'];
                $g_total = $paid_total + $free_total + $nr_total;

                // Accumulate totals
                $gt['gen_paid_opd'] += $row['gen_paid_opd'];
                $gt['gen_free_opd'] += $row['gen_free_opd'];
                $gt['opd_nr'] += $row['opd_nr'];
                $gt['opd_tot'] += $opd_tot;

                $gt['gen_paid_ipd'] += $row['gen_paid_ipd'];
                $gt['gen_free_ipd'] += $row['gen_free_ipd'];
                $gt['ipd_nr'] += $row['ipd_nr'];
                $gt['ipd_tot'] += $ipd_tot;

                $gt['gen_paid_emer'] += $row['gen_paid_emer'];
                $gt['gen_free_emer'] += $row['gen_free_emer'];
                $gt['nr_emer'] += $row['nr_emer'];
                $gt['emer_tot'] += $emer_tot;

                $gt['paid_total'] += $paid_total;
                $gt['free_total'] += $free_total;
                $gt['nr_total'] += $nr_total;
                $gt['g_total'] += $g_total;
                ?>
                <tr>
                    <td><?= $no++; ?></td>
                    <td><?= htmlspecialchars($row['param_name']); ?></td>

                    <td <?= highlight($row['gen_paid_opd']); ?>><?= $row['gen_paid_opd']; ?></td>
                    <td <?= highlight($row['gen_free_opd']); ?>><?= $row['gen_free_opd']; ?></td>
                    <td <?= highlight($row['opd_nr']); ?>><?= $row['opd_nr']; ?></td>
                    <td <?= total_highlight($opd_tot); ?>><?= $opd_tot; ?></td>

                    <td <?= highlight($row['gen_paid_ipd']); ?>><?= $row['gen_paid_ipd']; ?></td>
                    <td <?= highlight($row['gen_free_ipd']); ?>><?= $row['gen_free_ipd']; ?></td>
                    <td <?= highlight($row['ipd_nr']); ?>><?= $row['ipd_nr']; ?></td>
                    <td <?= total_highlight($ipd_tot); ?>><?= $ipd_tot; ?></td>

                    <td <?= highlight($row['gen_paid_emer']); ?>><?= $row['gen_paid_emer']; ?></td>
                    <td <?= highlight($row['gen_free_emer']); ?>><?= $row['gen_free_emer']; ?></td>
                    <td <?= highlight($row['nr_emer']); ?>><?= $row['nr_emer']; ?></td>
                    <td <?= total_highlight($emer_tot); ?>><?= $emer_tot; ?></td>

                    <td <?= highlight($paid_total); ?>><?= $paid_total; ?></td>
                    <td <?= highlight($free_total); ?>><?= $free_total; ?></td>
                    <td <?= highlight($nr_total); ?>><?= $nr_total; ?></td>
                    <td <?= g_total_highlight($g_total); ?>><?= $g_total; ?></td>
                </tr>
            <?php } ?>

            <!-- Grand total row -->
            <tr style="font-weight: bold; background-color: #d9e3ffff;">
                <td colspan="2" style="text-align: right;">Total: </td>

                <td><?= $gt['gen_paid_opd']; ?></td>
                <td><?= $gt['gen_free_opd']; ?></td>
                <td><?= $gt['opd_nr']; ?></td>
                <td><?= $gt['opd_tot']; ?></td>

                <td><?= $gt['gen_paid_ipd']; ?></td>
                <td><?= $gt['gen_free_ipd']; ?></td>
                <td><?= $gt['ipd_nr']; ?></td>
                <td><?= $gt['ipd_tot']; ?></td>

                <td><?= $gt['gen_paid_emer']; ?></td>
                <td><?= $gt['gen_free_emer']; ?></td>
                <td><?= $gt['nr_emer']; ?></td>
                <td><?= $gt['emer_tot']; ?></td>

                <td><?= $gt['paid_total']; ?></td>
                <td><?= $gt['free_total']; ?></td>
                <td><?= $gt['nr_total']; ?></td>
                <td><?= $gt['g_total']; ?></td>
            </tr>
        </tbody>
    </table>

    <?php
}
if ($_POST["type"] == 3) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];
    ?>


    <div>
        <p style="margin-top: 2%;"><b>Overall Test Wise Reports From:</b>
            <?php echo convert_date($fdate) . " <b>to</b> " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>
    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th rowspan="2">#</th>
                <th rowspan="2">Test Name</th>
                <th colspan="4">OPD</th>
                <th colspan="4">IPD</th>
                <th colspan="4">Emergency</th>
                <th colspan="4">Total</th>
            </tr>
            <tr>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
                <th>GEN(Paid)</th>
                <th>GEN(Free)</th>
                <th>NR</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php
            function highlight($value)
            {
                return $value > 0 ? ' style="background-color: #d4edda;"' : '';
            }

            function total_highlight($value)
            {
                return $value > 0 ? ' style="background-color: #fbffd9ff;"' : '';
            }

            function g_total_highlight($value)
            {
                return $value > 0 ? ' style="background-color: #d9e3ffff;"' : '';
            }

            // Initialize grand totals
            $gt = [
                'gen_paid_opd' => 0,
                'gen_free_opd' => 0,
                'opd_nr' => 0,
                'opd_tot' => 0,
                'gen_paid_ipd' => 0,
                'gen_free_ipd' => 0,
                'ipd_nr' => 0,
                'ipd_tot' => 0,
                'gen_paid_emer' => 0,
                'gen_free_emer' => 0,
                'nr_emer' => 0,
                'emer_tot' => 0,
                'paid_total' => 0,
                'free_total' => 0,
                'nr_total' => 0,
                'g_total' => 0
            ];
            $qry = "SELECT 
                a.testid,
                b.testname AS t_name,
                SUM(CASE WHEN ua.type = '1' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_opd,
                SUM(CASE WHEN ua.type = '1' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_opd,
                SUM(CASE WHEN ua.type = '3' AND ua.pat_type = 'OPD' THEN 1 ELSE 0 END) AS opd_nr,

                SUM(CASE WHEN ua.type = '2' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_ipd,
                SUM(CASE WHEN ua.type = '2' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_ipd,
                SUM(CASE WHEN ua.type = '3' AND ua.pat_type = 'IPD' THEN 1 ELSE 0 END) AS ipd_nr,

                SUM(CASE WHEN ua.type = '4' AND ua.free IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_paid_emer,
                SUM(CASE WHEN ua.type = '4' AND ua.free NOT IN (0,16,17,18) THEN 1 ELSE 0 END) AS gen_free_emer,
                SUM(CASE WHEN ua.type_prefix = 'NRM_EMRG/' THEN 1 ELSE 0 END) AS nr_emer
            FROM 
                testresults a
                JOIN testmaster b ON a.testid = b.testid
                JOIN uhid_and_opdid ua ON a.opd_id = ua.opd_id
            WHERE 
                a.date BETWEEN '$fdate' AND '$tdate'
            GROUP BY 
                a.testid
            ORDER BY 
                b.testname";
            $res = mysqli_query($link, $qry);
            $no = 1;

            while ($row = mysqli_fetch_assoc($res)) {
                $opd_tot = $row['gen_paid_opd'] + $row['gen_free_opd'] + $row['opd_nr'];
                $ipd_tot = $row['gen_paid_ipd'] + $row['gen_free_ipd'] + $row['ipd_nr'];
                $emer_tot = $row['gen_paid_emer'] + $row['gen_free_emer'] + $row['nr_emer'];

                $paid_total = $row['gen_paid_opd'] + $row['gen_paid_ipd'] + $row['gen_paid_emer'];
                $free_total = $row['gen_free_opd'] + $row['gen_free_ipd'] + $row['gen_free_emer'];
                $nr_total = $row['opd_nr'] + $row['ipd_nr'] + $row['nr_emer'];
                $g_total = $paid_total + $free_total + $nr_total;

                // Accumulate totals
                $gt['gen_paid_opd'] += $row['gen_paid_opd'];
                $gt['gen_free_opd'] += $row['gen_free_opd'];
                $gt['opd_nr'] += $row['opd_nr'];
                $gt['opd_tot'] += $opd_tot;

                $gt['gen_paid_ipd'] += $row['gen_paid_ipd'];
                $gt['gen_free_ipd'] += $row['gen_free_ipd'];
                $gt['ipd_nr'] += $row['ipd_nr'];
                $gt['ipd_tot'] += $ipd_tot;

                $gt['gen_paid_emer'] += $row['gen_paid_emer'];
                $gt['gen_free_emer'] += $row['gen_free_emer'];
                $gt['nr_emer'] += $row['nr_emer'];
                $gt['emer_tot'] += $emer_tot;

                $gt['paid_total'] += $paid_total;
                $gt['free_total'] += $free_total;
                $gt['nr_total'] += $nr_total;
                $gt['g_total'] += $g_total;
                ?>
                <tr>
                    <td><?= $no++; ?></td>
                    <td><?= htmlspecialchars($row['t_name']); ?></td>

                    <td <?= highlight($row['gen_paid_opd']); ?>><?= $row['gen_paid_opd']; ?></td>
                    <td <?= highlight($row['gen_free_opd']); ?>><?= $row['gen_free_opd']; ?></td>
                    <td <?= highlight($row['opd_nr']); ?>><?= $row['opd_nr']; ?></td>
                    <td <?= total_highlight($opd_tot); ?>><?= $opd_tot; ?></td>

                    <td <?= highlight($row['gen_paid_ipd']); ?>><?= $row['gen_paid_ipd']; ?></td>
                    <td <?= highlight($row['gen_free_ipd']); ?>><?= $row['gen_free_ipd']; ?></td>
                    <td <?= highlight($row['ipd_nr']); ?>><?= $row['ipd_nr']; ?></td>
                    <td <?= total_highlight($ipd_tot); ?>><?= $ipd_tot; ?></td>

                    <td <?= highlight($row['gen_paid_emer']); ?>><?= $row['gen_paid_emer']; ?></td>
                    <td <?= highlight($row['gen_free_emer']); ?>><?= $row['gen_free_emer']; ?></td>
                    <td <?= highlight($row['nr_emer']); ?>><?= $row['nr_emer']; ?></td>
                    <td <?= total_highlight($emer_tot); ?>><?= $emer_tot; ?></td>

                    <td <?= highlight($paid_total); ?>><?= $paid_total; ?></td>
                    <td <?= highlight($free_total); ?>><?= $free_total; ?></td>
                    <td <?= highlight($nr_total); ?>><?= $nr_total; ?></td>
                    <td <?= g_total_highlight($g_total); ?>><?= $g_total; ?></td>
                </tr>
            <?php } ?>

            <!-- Grand total row -->
            <tr style="font-weight: bold; background-color: #d9e3ffff;">
                <td colspan="2" style="text-align: right;">Total: </td>

                <td><?= $gt['gen_paid_opd']; ?></td>
                <td><?= $gt['gen_free_opd']; ?></td>
                <td><?= $gt['opd_nr']; ?></td>
                <td><?= $gt['opd_tot']; ?></td>

                <td><?= $gt['gen_paid_ipd']; ?></td>
                <td><?= $gt['gen_free_ipd']; ?></td>
                <td><?= $gt['ipd_nr']; ?></td>
                <td><?= $gt['ipd_tot']; ?></td>

                <td><?= $gt['gen_paid_emer']; ?></td>
                <td><?= $gt['gen_free_emer']; ?></td>
                <td><?= $gt['nr_emer']; ?></td>
                <td><?= $gt['emer_tot']; ?></td>

                <td><?= $gt['paid_total']; ?></td>
                <td><?= $gt['free_total']; ?></td>
                <td><?= $gt['nr_total']; ?></td>
                <td><?= $gt['g_total']; ?></td>
            </tr>
        </tbody>
    </table>

    <?php
}
?>