<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];




//------------------------------------------------------------------------------------------------//

// function getDatesFromRange($start, $end, $format = 'Y-m-d')
// {
//     $array = array();
//     $interval = new DateInterval('P1D');

//     $realEnd = new DateTime($end);
//     $realEnd->add($interval);

//     $period = new DatePeriod(new DateTime($start), $interval, $realEnd);

//     foreach ($period as $date) {
//         $array[] = $date->format($format);
//     }

//     return $array;
// }


$type = $_POST['type'];

if ($_POST["type"] == 2) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_report_opd('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Hospital Registration By Age Group - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>

    <table class="table table-condensed table-bordered" style="background-color: white;">
        <tr style="background-color: darkgray;">
            <th style="width:5%;">Age Label</th>
            <th style="width:7%;">Age timeframe</th>
            <th style="width:10%;" colspan="4">Total Registration</th>
            <th style="width:30%; text-align:center;">Visualization</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>Male</th>
            <th>Female</th>
            <th>Other</th>
            <th>Total</th>
            <td rowspan="10" style="vertical-align: top;">
                <div id="bar-chart" style="width: 100%; height: 600px;"></div>
            </td>
        </tr>

        <?php
        $new_born = $new_born_male = $new_born_female = $new_born_other = 0;
        $infant = $infant_male = $infant_female = $infant_other = 0;
        $toddler = $toddler_male = $toddler_female = $toddler_other = 0;
        $preschooler = $preschooler_male = $preschooler_female = $preschooler_other = 0;
        $child = $child_male = $child_female = $child_other = 0;
        $adolescent = $adolescent_male = $adolescent_female = $adolescent_other = 0;
        $young_adult = $young_adult_male = $young_adult_female = $young_adult_other = 0;
        $adult = $adult_male = $adult_female = $adult_other = 0;
        $senior_elderly = $senior_elderly_male = $senior_elderly_female = $senior_elderly_other = 0;


        $pat_reg_qry = mysqli_query($link, "SELECT DATEDIFF(STR_TO_DATE(b.date, '%Y-%m-%d'), STR_TO_DATE(a.dob, '%Y-%m-%d')) AS `age_in_days`, STR_TO_DATE(a.dob, '%Y-%m-%d') AS `dob`, STR_TO_DATE(b.date, '%Y-%m-%d') AS `reg_date`, a.sex FROM `patient_info` a, `uhid_and_opdid` b WHERE a.patient_id = b.patient_id AND b.`type` = 2 AND STR_TO_DATE(b.date, '%Y-%m-%d') BETWEEN STR_TO_DATE('$fdate', '%Y-%m-%d') AND STR_TO_DATE('$tdate', '%Y-%m-%d')");

        // echo "SELECT DATEDIFF(STR_TO_DATE(b.date, '%Y-%m-%d'), STR_TO_DATE(a.dob, '%Y-%m-%d')) AS `age_in_days`, STR_TO_DATE(a.dob, '%Y-%m-%d') AS `dob`, STR_TO_DATE(b.date, '%Y-%m-%d') AS `reg_date`, a.sex FROM `patient_info` a, `uhid_and_opdid` b WHERE a.patient_id = b.patient_id AND b.`type` = 2 AND STR_TO_DATE(b.date, '%Y-%m-%d') BETWEEN STR_TO_DATE('$fdate', '%Y-%m-%d') AND STR_TO_DATE('$tdate', '%Y-%m-%d')";
    
        // echo "SELECT DATEDIFF(b.date,STR_TO_DATE(a.dob, '%d-%m-%Y')) AS `age_in_days`, STR_TO_DATE(a.dob, '%d-%m-%Y') AS `dob`,b.date AS `reg_date`,a.sex FROM `patient_info` a, `uhid_and_opdid` b WHERE a.patient_id=b.patient_id AND b.`type`= 2 AND b.`date` BETWEEN '$fdate' AND '$tdate'";
    
        while ($pat_reg = mysqli_fetch_array($pat_reg_qry)) {
            if ($pat_reg["age_in_days"] < 31) {
                if ($pat_reg["sex"] == "Male") {
                    $new_born_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $new_born_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $new_born_other++;
                }
                $new_born++;
            } else if ($pat_reg["age_in_days"] > 30 && $pat_reg["age_in_days"] < 365) {
                if ($pat_reg["sex"] == "Male") {
                    $infant_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $infant_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $infant_other++;
                }
                $infant++;
            } else if ($pat_reg["age_in_days"] > 365 && $pat_reg["age_in_days"] < 1095) {
                if ($pat_reg["sex"] == "Male") {
                    $toddler_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $toddler_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $toddler_other++;
                }
                $toddler++;
            } else if ($pat_reg["age_in_days"] > 1095 && $pat_reg["age_in_days"] < 1825) {
                if ($pat_reg["sex"] == "Male") {
                    $preschooler_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $preschooler_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $preschooler_other++;
                }
                $preschooler++;
            } else if ($pat_reg["age_in_days"] > 1825 && $pat_reg["age_in_days"] < 4380) {
                if ($pat_reg["sex"] == "Male") {
                    $child_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $child_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $child_other++;
                }
                $child++;
            } else if ($pat_reg["age_in_days"] > 4380 && $pat_reg["age_in_days"] < 6570) {
                if ($pat_reg["sex"] == "Male") {
                    $adolescent_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $adolescent_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $adolescent_other++;
                }
                $adolescent++;
            } else if ($pat_reg["age_in_days"] > 6570 && $pat_reg["age_in_days"] < 9125) {
                if ($pat_reg["sex"] == "Male") {
                    $young_adult_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $young_adult_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $young_adult_other++;
                }
                $young_adult++;
            } else if ($pat_reg["age_in_days"] > 9125 && $pat_reg["age_in_days"] < 23725) {
                if ($pat_reg["sex"] == "Male") {
                    $adult_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $adult_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $adult_other++;
                }
                $adult++;
            } else if ($pat_reg["age_in_days"] > 23725) {
                if ($pat_reg["sex"] == "Male") {
                    $senior_elderly_male++;
                } else if ($pat_reg["sex"] == "Female") {
                    $senior_elderly_female++;
                } else if ($pat_reg["sex"] == "Other") {
                    $senior_elderly_other++;
                }
                $senior_elderly++;
            }
        }
        ?>
        <tr>
            <td>Newborn</td>
            <td>0 – 1 month</td>
            <td><?php echo $new_born_male; ?></td>
            <td><?php echo $new_born_female; ?></td>
            <td><?php echo $new_born_other; ?></td>
            <td><?php echo $new_born; ?></td>
        </tr>
        <tr>
            <td>Infant</td>
            <td>1 – 12 months</td>
            <td><?php echo $infant_male; ?></td>
            <td><?php echo $infant_female; ?></td>
            <td><?php echo $infant_other; ?></td>
            <td><?php echo $infant; ?></td>
        </tr>
        <tr>
            <td>Toddler</td>
            <td>1 – 3 years</td>
            <td><?php echo $toddler_male; ?></td>
            <td><?php echo $toddler_female; ?></td>
            <td><?php echo $toddler_other; ?></td>
            <td><?php echo $toddler; ?></td>
        </tr>
        <tr>
            <td>Preschooler</td>
            <td>3 – 5 years</td>
            <td><?php echo $preschooler_male; ?></td>
            <td><?php echo $preschooler_female; ?></td>
            <td><?php echo $preschooler_other; ?></td>
            <td><?php echo $preschooler; ?></td>
        </tr>
        <tr>
            <td>Child</td>
            <td>5 – 12 years</td>
            <td><?php echo $child_male; ?></td>
            <td><?php echo $child_female; ?></td>
            <td><?php echo $child_other; ?></td>
            <td><?php echo $child; ?></td>
        </tr>
        <tr>
            <td>Adolescent (Teen)</td>
            <td>12 – 18 years</td>
            <td><?php echo $adolescent_male; ?></td>
            <td><?php echo $adolescent_female; ?></td>
            <td><?php echo $adolescent_other; ?></td>
            <td><?php echo $adolescent; ?></td>
        </tr>
        <tr>
            <td>Young Adult</td>
            <td>18 – 25 years</td>
            <td><?php echo $young_adult_male; ?></td>
            <td><?php echo $young_adult_female; ?></td>
            <td><?php echo $young_adult_other; ?></td>
            <td><?php echo $young_adult; ?></td>
        </tr>
        <tr>
            <td>Adult</td>
            <td>25 – 65 years</td>
            <td><?php echo $adult_male; ?></td>
            <td><?php echo $adult_female; ?></td>
            <td><?php echo $adult_other; ?></td>
            <td><?php echo $adult; ?></td>
        </tr>
        <tr>
            <td>Senior/Elderly</td>
            <td>65 years and above</td>
            <td><?php echo $senior_elderly_male; ?></td>
            <td><?php echo $senior_elderly_female; ?></td>
            <td><?php echo $senior_elderly_other; ?></td>
            <td><?php echo $senior_elderly; ?></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:right;"><b>Total :</b></td>
            <td><?php echo $new_born_male + $infant_male + $toddler_male + $preschooler_male + $child_male + $adolescent_male + $young_adult_male + $adult_male + $senior_elderly_male; ?>
            </td>
            <td><?php echo $new_born_female + $infant_female + $toddler_female + $preschooler_female + $child_female + $adolescent_female + $young_adult_female + $adult_female + $senior_elderly_female; ?>
            </td>
            <td><?php echo $new_born_other + $infant_other + $toddler_other + $preschooler_other + $child_other + $adolescent_other + $young_adult_other + $adult_other + $senior_elderly_other; ?>
            </td>
            <td><?php echo $new_born + $infant + $toddler + $preschooler + $child + $adolescent + $young_adult + $adult + $senior_elderly; ?>
            </td>
            <td></td>
        </tr>
    </table>

    <script>
        const departments = ["Newborn", "Infant", "Toddler", "Preschooler", "Child", "Adolescent", "Young Adult", "Adult", "Senior/Elderly"];
        const maleCounts = [<?php echo $new_born_male; ?>, <?php echo $infant_male; ?>, <?php echo $toddler_male; ?>, <?php echo $preschooler_male; ?>, <?php echo $child_male; ?>, <?php echo $adolescent_male; ?>, <?php echo $young_adult_male; ?>, <?php echo $adult_male; ?>, <?php echo $senior_elderly_male; ?>];
        const femaleCounts = [<?php echo $new_born_female; ?>, <?php echo $infant_female; ?>, <?php echo $toddler_female; ?>, <?php echo $preschooler_female; ?>, <?php echo $child_female; ?>, <?php echo $adolescent_female; ?>, <?php echo $young_adult_female; ?>, <?php echo $adult_female; ?>, <?php echo $senior_elderly_female; ?>];
        const otherCounts = [<?php echo $new_born_other; ?>, <?php echo $infant_other; ?>, <?php echo $toddler_other; ?>, <?php echo $preschooler_other; ?>, <?php echo $child_other; ?>, <?php echo $adolescent_other; ?>, <?php echo $young_adult_other; ?>, <?php echo $adult_other; ?>, <?php echo $senior_elderly_other; ?>];

        const data = [
            {
                type: 'bar',
                name: 'Male',
                x: departments,
                y: maleCounts,
                marker: { color: '#637ACB' },
            },
            {
                type: 'bar',
                name: 'Female',
                x: departments,
                y: femaleCounts,
                marker: { color: 'pink' },
            },
            {
                type: 'bar',
                name: 'Other',
                x: departments,
                y: otherCounts,
                marker: { color: 'grey' },
            }
        ];

        const layout = {
            title: 'Hospital Registration by Age Group and Gender',
            xaxis: { title: 'Age Group' },
            yaxis: { title: 'Total Registrations' },
            barmode: 'stack',
            height: 600,
        };

        Plotly.newPlot('bar-chart', data, layout);
        $(".modebar").remove();

    </script>

    <?php

}




