<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];


$type = $_POST['type'];


if ($_POST["type"] == 2) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_inv_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Test Wise Reports - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th style="width:18%;">Test Name</th>
                <th style="width:8%;">OPD Test Count</th>
                <th style="width:8%;">IPD Test Count</th>
                <th style="width:7%;">Total Count</th>
                <th>Visualization</th>
            </tr>
        </thead>

        <?php
        $test_name = mysqli_query($link, "SELECT DISTINCT b.`testid`,b.`testname` FROM `patient_test_details` a, `testmaster` b WHERE a.testid=b.testid AND b.type_id='29' AND a.ipd_id='' AND a.date BETWEEN '$fdate' AND '$tdate' ORDER BY b.testname ASC ");

        $total_opd = 0;
        $total_ipd = 0;
        $grand_total = 0;

        $tests = [];
        $opdCounts = [];
        $ipdCounts = [];

        $row_counter = 0;

        while ($test = mysqli_fetch_array($test_name)) {
            $opd_count = mysqli_fetch_array(mysqli_query($link, "SELECT ifnull(COUNT(`testid`),0) AS `total` FROM `patient_test_details` WHERE `testid`='$test[testid]' AND ipd_id='' AND date BETWEEN '$fdate' AND '$tdate' "));
            $ipd_count = mysqli_fetch_array(mysqli_query($link, "SELECT ifnull(COUNT(`testid`),0) AS `total` FROM `patient_test_details` WHERE `testid`='$test[testid]' AND opd_id='' AND date BETWEEN '$fdate' AND '$tdate' "));

            $total_test = $opd_count['total'] + $ipd_count['total'];

            $total_opd += $opd_count['total'];
            $total_ipd += $ipd_count['total'];
            $grand_total += $total_test;

            if ($total_test > 0) {
                $tests[] = $test['testname'];
                $opdCounts[] = $opd_count['total'];
                $ipdCounts[] = $ipd_count['total'];
                $row_counter++;
                ?>
                <tr>
                    <td><?php echo $test['testname']; ?></td>
                    <td><?php echo $opd_count['total']; ?></td>
                    <td><?php echo $ipd_count['total']; ?></td>
                    <td><?php echo $total_test; ?></td>
                    <?php if ($row_counter == 1) { ?>
                        <td rowspan="<?php echo mysqli_num_rows($test_name); ?>">
                            <div id="chart-container" style="height: 600px;"></div>
                        </td>
                    <?php } ?>
                </tr>
                <?php
            }
        }
        ?>
        <tfoot>
            <tr>
                <th>Total :</th>
                <th><?php echo $total_opd; ?></th>
                <th><?php echo $total_ipd; ?></th>
                <th><?php echo $grand_total; ?></th>
                <th></th>
            </tr>
        </tfoot>
    </table>

    <script>
        const tests = <?php echo json_encode($tests); ?>;
        const opdCounts = <?php echo json_encode($opdCounts); ?>;
        const ipdCounts = <?php echo json_encode($ipdCounts); ?>;

        const data = [
            {
                type: 'bar',
                name: 'OPD Test Count',
                x: tests,
                y: opdCounts,
                marker: { color: 'light blue' },
            },
            {
                type: 'bar',
                name: 'IPD Test Count',
                x: tests,
                y: ipdCounts,
                marker: { color: 'orange' },
            }
        ];

        const layout = {
            title: 'Test Metrics Visualization',
            xaxis: { title: 'Test Names' },
            yaxis: { title: 'Test Count' },
            barmode: 'stack',
            height: 600,
        };

        Plotly.newPlot('chart-container', data, layout);
        $(".modebar").remove();
    </script>
    <?php
}



