<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];




//------------------------------------------------------------------------------------------------//

// function getDatesFromRange($start, $end, $format = 'Y-m-d')
// {
//     $array = array();
//     $interval = new DateInterval('P1D');

//     $realEnd = new DateTime($end);
//     $realEnd->add($interval);

//     $period = new DatePeriod(new DateTime($start), $interval, $realEnd);

//     foreach ($period as $date) {
//         $array[] = $date->format($format);
//     }

//     return $array;
// }


$type = $_POST['type'];
if ($_POST["type"] == 1) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];
    $free_pat = $_POST['free_typ'];


    ?>

    <div>
        <p style="margin-top: 2%;"><b>Overall Compasionate Care Reports - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_scheme_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>','<?php echo $free_pat; ?>')">Print</button>
    </div>

    <?php
    $free_label = "All Free Types";

    if ($free_pat != "0") {
        $name_qry = mysqli_query($link, "SELECT `name` FROM `free_type_master` WHERE `code` = '$free_pat'");
        $name_row = mysqli_fetch_array($name_qry);
        $free_label = $name_row ? $name_row['name'] : strtoupper($free_pat);
    }

    $count_sql = "SELECT COUNT(DISTINCT u.patient_id, u.opd_id) AS total_patients
              FROM uhid_and_opdid u
              INNER JOIN patient_test_details t ON u.patient_id = t.patient_id AND u.opd_id = t.opd_id";

    if ($free_pat != "0") {
        $count_sql .= " WHERE u.freeType = '$free_pat' AND u.date BETWEEN '$fdate' AND '$tdate'";
    } else {
        $count_sql .= " WHERE u.date BETWEEN '$fdate' AND '$tdate'";
    }

    $count_result = mysqli_query($link, $count_sql);
    $count_data = mysqli_fetch_array($count_result);
    $total_patients = $count_data['total_patients'];
    ?>

    <div
        style="margin: 15px 0; padding: 10px; background-color: #f4f8fc; border-left: 4px solid #007bff; font-size: 17px; font-weight: bold; color: #333;">
        <?php echo $free_label; ?> - Total Patients = <span style="color: #007bff;"><?php echo $total_patients; ?></span>
    </div>


    <div class="scrollable-table">
        <table class="table table-bordered text-center">
            <thead class="table_header_fix">
                <tr style="background-color: light-grey;">
                    <th>Slno</th>
                    <th>Patient Name</th>
                    <th>Hospital No.</th>
                    <th>Cash Memo No.</th>
                    <th>Amount</th>
                    <th>Discount</th>
                    <th>Total Amount</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $n = 1;

                $sql = "SELECT u.`patient_id`, u.`opd_id`, u.`hospital_no`, u.`cashMemoNo`, u.`wardName`, u.`date`, u.`freeType`, u.`schemeName`, u.`discountAmt`, u.`reg_type`, p.name, SUM(t.test_rate) AS total_rate 
                FROM uhid_and_opdid u 
                INNER JOIN patient_test_details t ON u.patient_id = t.patient_id AND u.opd_id = t.opd_id 
                INNER JOIN patient_info p ON u.patient_id = p.patient_id 
                WHERE u.date BETWEEN '$fdate' AND '$tdate'";

                if ($free_pat != "0") {
                    $sql .= " AND u.freeType = '$free_pat'";
                }

                $sql .= " GROUP BY u.patient_id, u.opd_id";

                $free_qry = mysqli_query($link, $sql);

                while ($free = mysqli_fetch_array($free_qry)) {
                    $total_amount = $free['total_rate'] - $free['discountAmt'];
                    ?>
                    <tr>
                        <td><?php echo $n++; ?></td>
                        <td><?php echo $free['name']; ?></td>
                        <td><?php echo $free['hospital_no']; ?></td>
                        <td><?php echo $free['cashMemoNo']; ?></td>
                        <td><?php echo number_format($free['total_rate'], 2); ?></td>
                        <td><?php echo number_format($free['discountAmt'], 2); ?></td>
                        <td><?php echo number_format($total_amount, 2); ?></td>
                        <td><?php echo $free['date']; ?></td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>


        </table>
    </div>


    <style>
        .scrollable-table {
            max-height: 500px;
            overflow-y: scroll;
        }

        .scrollable-table thead th {
            position: sticky;
            top: 0;
            z-index: 1;
        }

        @media print {
            .scrollable-table {
                max-height: none !important;
                overflow: visible !important;
            }

            .scrollable-table thead th {
                position: static !important;
            }
        }

        @media print {
            .no-print {
                display: none !important;
            }
        }
    </style>


    <!-- <style>
        .ScrollStyleY {
            max-height: 450px;
            overflow-y: scroll;
        }
    </style> -->

    <?php
}






