<?php
session_start();

include("../../includes/connection.php");
include("../../includes/global.function.php");


$date = date("Y-m-d");
$time = date('H:i:s');
$user = $_SESSION["emp_id"];


$type = $_POST['type'];


if ($_POST["type"] == 1) {
    $fdate = $_POST['fdate'];
    $tdate = $_POST['tdate'];

    ?>
    <div style="text-align:right;">
        <button type="button" class="btn btn-primary" id="act_btn"
            onclick="print_total_reg_report('<?php echo $fdate; ?>','<?php echo $tdate; ?>','<?php echo $type; ?>')">Print</button>
    </div>
    <div>
        <p style="margin-top: 2%;"><b>Overall Registrations - from:</b>
            <?php echo convert_date($fdate) . " to " . convert_date($tdate); ?>
        </p>

        <?php
        $user_nm = mysqli_fetch_array(mysqli_query($link, "SELECT `name` FROM `employee` WHERE `emp_id`='$user'"));
        ?>
        <p>
            <b>Reported Generated By: <?php echo $user_nm['name']; ?></b>
        </p>
    </div>
    <style>
        .table_header_fix th {
            background-color: rgb(184, 185, 185);
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
            border: 1.5px solid #ddd;
        }
    </style>
    <table class="table table-bordered text-center">
        <thead class="table_header_fix">
            <tr>
                <th>Slno.</th>
                <th>Registration Types</th>
                <th>Total Patients</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $n = 1;

            $pat_types = mysqli_query($link, "
        SELECT DISTINCT `type_prefix`, `pat_type` 
        FROM `uhid_and_opdid` 
        WHERE `date` BETWEEN '$fdate' AND '$tdate' 
        ORDER BY `type_prefix` ASC
    ");

            while ($row = mysqli_fetch_array($pat_types)) {
                $type_prefix = $row['type_prefix'];
                $pat_type = $row['pat_type'];

                switch ($type_prefix) {
                    case 'EC/':
                        $display_name = 'Emergency';
                        break;
                    case 'P_NR_EC_I/':
                        $display_name = 'NRHM Emergency (IPD)';
                        break;
                    case 'P_NR_EC_O/':
                        $display_name = 'NRHM Emergency (OPD)';
                        break;
                    case 'IPD_BIO/':
                        $display_name = 'IPD';
                        break;
                    case 'P_NR_I/':
                        $display_name = 'NRHM (IPD)';
                        break;
                    case 'P_OPD/':
                        $display_name = 'OPD';
                        break;
                    case 'P_NR_O/':
                        $display_name = 'NRHM (OPD)';
                        break;
                    default:
                        $display_name = $type_prefix;
                }

                $total_patients = mysqli_num_rows(mysqli_query($link, "
                    SELECT * FROM `uhid_and_opdid` 
                    WHERE `date` BETWEEN '$fdate' AND '$tdate' 
                    AND `type_prefix` = '$type_prefix' 
                    AND `pat_type` = '$pat_type'
                "));
                ?>
                <tr>
                    <td><?php echo $n++; ?></td>
                    <td><?php echo $display_name; ?></td>
                    <td><?php echo $total_patients; ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>


        <tfoot>
            <tr>
                <td colspan="2"><strong>Total Registrations</strong></td>
                <td>
                    <?php
                    $total_registrations = mysqli_num_rows(mysqli_query($link, "
                SELECT * FROM `uhid_and_opdid` 
                WHERE `date` BETWEEN '$fdate' AND '$tdate'
            "));
                    echo $total_registrations;
                    ?>
                </td>
            </tr>
        </tfoot>
    </table>



    <?php
}




